---
title: "Introduction to `wildcam`"
author: "Alec L. Robitaille"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


# What you'll need
* study area polygon
* layers of relevant variables (e.g. roads, animal density, waterways, etc.)
* camera trap protocol (how many cameras, placement strategy)



# Selecting potential camera trap locations
## Randomly sampling points in different regions (stratified sampling)

```{r}
# Example polygons with density levels 1, 2 and 3.
data(densitygrid)
#'
# Randomly sample 5 points for each set of polygons in each strata.
pts <- strat_sample(x = densitygrid, n = 5, col = 'density', returnDT = FALSE)
#'
plot(densitygrid, reset = FALSE)
plot(pts$geometry, add = TRUE)

```

## Grid around points

```{r}
queen <- make_grid(pts, case = 'queen', distance = 100)
plot(queen)

rook <- make_grid(pts, case = 'rook', distance = 100)
plot(rook)

bishop <- make_grid(pts, case = 'bishop', distance = 100)
plot(bishop)
```